BUG: prevent user's OR query from clashing with auth
joindeed/prisma-auth pull request #12
Opened 2023-01-11 15:49 UTC by dimaip

Currently prisma-auth works like this:

```js
const authCondition = {
  OR: [{ communityId: <communityId>}]
}
const userQuery = {
  OR: [{ some: <thing>}]
}
const mergedQuery = {
  OR: [{ communityId: <communityId>}, { some: <thing>}]
}
```
which obviously breaks both the auth and the query.

The new logic is this:

```js
const authCondition = {
  AND: [{
    OR: [{ communityId: <communityId>}]
  }]
}
const userQuery = {
  OR: [{ some: <thing>}]
}
const mergedQuery = {
  AND: [{
    OR: [{ communityId: <communityId>}]
  }],
  OR: [{ some: <thing>}]
}
```
Which enforces both the user's condition AND the auth query.

2023-01-11 16:09 UTC, ohnoimdead requested changes
Would be nice to have a test verifying correct behavior in: https://github.com/joindeed/prisma-auth/blob/main/src/getListWhereConstrains.test.ts

2023-01-11 16:27 UTC, dimaip commented
> Would be nice to have a test verifying correct behavior in: https://github.com/joindeed/prisma-auth/blob/main/src/getListWhereConstrains.test.ts

Yeah, on it

2023-01-12 07:59 UTC, hafizalfaza approved these changes
reads sensibly to me

2023-01-12 09:14 UTC, cassiohub approved these changes
It does makes sense. Additional auth constraints will be included on the `AND` clause level, right?

2023-01-12 09:25 UTC, dimaip commented
> It does make sense. Additional auth constraints will be included on the `AND` clause level, right?

prisma-auth constraints are wrapped inside AND, user constraints remain at lop level, and they will be automatically ANDed with the auth ones.

2023-01-16 09:45 UTC, ohnoimdead approved these changes

2023-01-16 09:45 UTC, merged